In [4]:
import numpy as np 
import pandas as pd 
pd.set_option('display.max_columns', None)
import os

In [5]:
ROOT_PATH = "CMaps"
METADATA = ['readme.txt', 'x.txt', 'Damage Propagation Modeling.pdf']
DATA_TXT = []

for file in os.listdir(ROOT_PATH):
    if file not in METADATA:
        DATA_TXT.append(file)
DATA_TXT

['train_FD001.txt',
 'train_FD003.txt',
 'RUL_FD004.txt',
 'train_FD002.txt',
 'RUL_FD001.txt',
 'RUL_FD003.txt',
 'RUL_FD002.txt',
 'train_FD004.txt',
 'test_FD003.txt',
 'test_FD002.txt',
 'test_FD001.txt',
 'test_FD004.txt']

In [16]:
cols = {
    "engine" : "Engine No.",
    "cycle" : "Time, In Cycles",
    "setting1" : "Operation Setting 1",
    "setting2" : "Operation Setting 2",
    "setting3" : "Operation Setting 3",
    "sensor1" : "Fan Inlet Temperature (◦R)",
    "sensor2" : "LPC Outlet Temperature (◦R)",
    "sensor3" : "HPC Outlet Temperature (◦R)",
    "sensor4" : "LPT Outlet Temperature (◦R)",
    "sensor5" : "Fan Inlet Pressure (psia)",
    "sensor6" : "Bypass-Duct Pressure (psia)",
    "sensor7" : "HPC Outlet Pressure (psia)",
    "sensor8" : "Physical Fan Speed (rpm)",
    "sensor9" : "Physical Core Speed (rpm)",
    "sensor10" : "Engine Pressure Ratio(P50/P2)",
    "sensor11" : "HPC Outlet Static Pressure (psia)",
    "sensor12" : "Ratio of Fuel Flow to Ps30 (pps/psia)",
    "sensor13" : "Corrected Fan Speed (rpm)",
    "sensor14" : "Corrected Core Speed (rpm)",
    "sensor15" : "Bypass Ratio",
    "sensor16" : "Burner Fuel-Air Ratio",
    "sensor17" : "Bleed Enthalpy",
    "sensor18" : "Required Fan Speed",
    "sensor19" : "Required Fan Conversion Speed",
    "sensor20" : "High-Pressure Turbines Cool Air Flow",
    "sensor21" : "Low-Pressure Turbines Cool Air Flow"
}

In [48]:
train_df = pd.DataFrame()
test_df = pd.DataFrame()
rul_df = pd.DataFrame()

for file in DATA_TXT:
    if 'train' in file:
        df = pd.read_csv(os.path.join(ROOT_PATH, file), sep=' ', header=None)
        # df['file_name'] = file
        train_df = pd.concat([train_df, df], axis=0)
    elif 'test' in file:
        df = pd.read_csv(os.path.join(ROOT_PATH, file), sep=' ', header=None)
        # print(df.shape)
        # df['file_name'] = file
        test_df = pd.concat([test_df, df], axis=0)
    elif 'RUL' in file:
        df =  pd.read_csv(os.path.join(ROOT_PATH, file), sep=' ', header=None)
        # rul_df['file_name'] = file
        rul_df = pd.concat([rul_df, df], axis=0)
        
train_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,21.61,554.36,2388.06,9046.19,1.3,47.47,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190,NaN,NaN
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,21.61,553.75,2388.04,9044.07,1.3,47.49,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,NaN,NaN
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,21.61,554.26,2388.08,9052.94,1.3,47.27,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,NaN,NaN
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,21.61,554.45,2388.11,9049.48,1.3,47.13,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,NaN,NaN
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,21.61,554.00,2388.06,9055.15,1.3,47.28,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,NaN,NaN

In [49]:
col_names = list(cols.values())

In [51]:
train_df = train_df[train_df.columns[:-2]]
test_df = test_df[test_df.columns[:-2]]

In [53]:
train_df.columns = col_names
test_df.columns = col_names

In [55]:
train_df['Engine No.'].max()

260

In [64]:
rul_df = rul_df[rul_df.columns[:-1]]

In [65]:
train_df.to_csv('processed_train.csv', index=False)
test_df.to_csv('processed_test.csv', index=False)
rul_df.to_csv('rul.csv', index=False)

In [66]:
rul_df

       0
0     22
1     39
2    107
3     75
4    149
..   ...
254  122
255  191
256   56
257  131
258   51

[707 rows x 1 columns]